[2024-11-18 13:57:08,851] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.9:5000 - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-18 13:57:08,853] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-18 13:57:08,855] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-18 14:05:26,921] INFO _log() L97   127.0.0.1 - - [18/Nov/2024 14:05:26] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-18 14:05:26,967] INFO _log() L97   127.0.0.1 - - [18/Nov/2024 14:05:26] "[32mGET /openapi HTTP/1.1[0m" 308 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-18 14:05:26,994] INFO _log() L97   127.0.0.1 - - [18/Nov/2024 14:05:26] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:01,590] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.225.93.169:5000 - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:01,592] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:01,593] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:05,065] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:05] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:05,137] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:05] "[32mGET /openapi HTTP/1.1[0m" 308 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:05,174] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:05] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:05,444] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:05] "GET /openapi/redoc/images/redoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:05,447] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:05] "GET /openapi/rapidoc/images/rapidoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:05,451] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:05] "GET /openapi/swagger/images/swagger.svg HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:06,858] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:06] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:06,871] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:06] "GET /openapi/swagger/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:06,881] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:06] "GET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:06,946] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:06] "GET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:07,278] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:07] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:07,328] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:07] "[36mGET /openapi/swagger/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:15,020] ERROR log_exception() L875  Exception on /progressao [GET] - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "C:\Users\t3uq\git\mvp-api\app.py", line 99, in get_progressao
    logger.debug(f"Coletando dados sobre a progressão #{progressao_id}")
                                                        ^^^^^^^^^^^^^
NameError: name 'progressao_id' is not defined. Did you mean: 'progressao'?
[2024-11-19 09:02:15,035] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:15] "[35m[1mGET /progressao?cod_mapa=10 HTTP/1.1[0m" 500 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:27,456] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:27] "GET /progressoes HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:29,231] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:29] "GET /progressoes HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:49,948] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:49] "POST /progressao HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:02:58,367] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:02:58] "POST /progressao HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:03:04,158] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:03:04] "POST /progressao HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:03:11,749] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:03:11] "GET /progressoes HTTP/1.1" 200 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-11-19 09:03:24,364] ERROR log_exception() L875  Exception on /progressao [DELETE] - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "C:\Users\t3uq\git\mvp-api\app.py", line 125, in del_progressao
    progressao_id = unquote(unquote(query.id))
                                    ^^^^^^^^
  File "C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\pydantic\main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ProgressaoBuscaSchema' object has no attribute 'id'
[2024-11-19 09:03:24,381] INFO _log() L97   127.0.0.1 - - [19/Nov/2024 09:03:24] "[35m[1mDELETE /progressao?cod_mapa=10 HTTP/1.1[0m" 500 - - call_trace=C:\Users\t3uq\git\mvp-api\env\Lib\site-packages\werkzeug\_internal.py L97  
